'use strict';

/**
 * seedOpportunities.js
 *
 * Inserts a curated set of South African job opportunities.
 * Called automatically by seed.js on startup when the database is empty,
 * or manually: node scripts/seedOpportunities.js
 */

require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');

function getSupabase() {
  if (!process.env.SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) {
    throw new Error('SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set');
  }
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, {
    auth: { autoRefreshToken: false, persistSession: false },
  });
}

function daysFromNow(days) {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

const OPPORTUNITIES = [
  {
    title: 'Junior Software Developer',
    type: 'full-time',
    company: 'Synthesis Technology',
    location: 'Cape Town, Western Cape',
    province: ['Western Cape'],
    description: 'Join our growing engineering team building financial technology platforms. You will work on React frontends and Node.js APIs, collaborate in agile sprints, and receive mentorship from senior developers. Great opportunity for a graduate looking to grow quickly.',
    requirements: ['BSc Computer Science or equivalent', 'Proficiency in JavaScript', 'Git version control', 'Problem-solving mindset'],
    skills: ['JavaScript', 'React', 'Node.js', 'Git', 'REST APIs'],
    salary_range: { min: 20000, max: 30000 },
    deadline: daysFromNow(45),
    application_url: 'https://synthesis.co.za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'IT Support Technician',
    type: 'full-time',
    company: 'Neotel Business Solutions',
    location: 'Johannesburg, Gauteng',
    province: ['Gauteng'],
    description: 'Provide first-line and second-line IT support to a corporate client base. Responsibilities include hardware troubleshooting, software installation, network diagnostics, and maintaining IT documentation. ITIL certification is advantageous.',
    requirements: ['Matric + IT diploma', '1–2 years helpdesk experience', 'CompTIA A+ or N+ preferred', 'Strong communication skills'],
    skills: ['Windows', 'Active Directory', 'Hardware Support', 'Networking', 'Ticketing Systems'],
    salary_range: { min: 12000, max: 18000 },
    deadline: daysFromNow(30),
    application_url: 'https://neotel.co.za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Data Analyst',
    type: 'full-time',
    company: 'Woolworths Financial Services',
    location: 'Pretoria, Gauteng',
    province: ['Gauteng'],
    description: 'Analyse customer data to drive retail and credit decisions. You will build dashboards in Power BI, write SQL queries against large datasets, and present findings to business stakeholders. Experience in Python or R is a strong plus.',
    requirements: ['BCom Statistics / Mathematics or relevant degree', 'SQL proficiency', 'Power BI or Tableau', '1+ year analytical experience'],
    skills: ['SQL', 'Power BI', 'Python', 'Excel', 'Data Visualisation', 'Statistics'],
    salary_range: { min: 25000, max: 40000 },
    deadline: daysFromNow(60),
    application_url: 'https://woolworths.co.za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Digital Marketing Coordinator',
    type: 'full-time',
    company: 'The Social Lab',
    location: 'Cape Town, Western Cape',
    province: ['Western Cape'],
    description: 'Manage paid and organic social campaigns across Facebook, Instagram, TikTok, and LinkedIn for a portfolio of FMCG and lifestyle brands. You will plan content calendars, run A/B tests on creatives, and report on KPIs weekly.',
    requirements: ['Marketing / Communications degree or equivalent', 'Meta Business Suite experience', 'Copywriting skills', 'Google Analytics'],
    skills: ['Social Media Marketing', 'Content Creation', 'Google Analytics', 'SEO', 'Copywriting', 'Meta Ads'],
    salary_range: { min: 15000, max: 24000 },
    deadline: daysFromNow(40),
    application_url: 'https://thesociallab.co.za/join-us',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'HR Administrator',
    type: 'full-time',
    company: 'Bidvest Group',
    location: 'Johannesburg, Gauteng',
    province: ['Gauteng'],
    description: 'Support the HR department with recruitment coordination, onboarding, payroll input, leave administration, and HRIS system management. You will work closely with line managers and the HR business partner team.',
    requirements: ['HR Diploma or BCom HR Management', 'Payroll system experience (VIP/Sage)', 'Organised and detail-orientated', 'MIBFA/NBCRFLI knowledge advantageous'],
    skills: ['HR Administration', 'Payroll', 'Recruitment', 'HRIS', 'Microsoft Office', 'LRA compliance'],
    salary_range: { min: 14000, max: 22000 },
    deadline: daysFromNow(35),
    application_url: 'https://bidvest.com/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Junior Financial Analyst',
    type: 'full-time',
    company: 'Absa Corporate and Investment Banking',
    location: 'Sandton, Gauteng',
    province: ['Gauteng'],
    description: 'Support the financial analysis team with financial modelling, variance analysis, budget preparation, and monthly reporting. You will gain exposure to corporate finance transactions and work alongside experienced analysts.',
    requirements: ['BCom Accounting / Finance', 'CFA Level 1 advantageous', 'Advanced Excel', 'Strong numerical aptitude'],
    skills: ['Financial Modelling', 'Excel', 'Financial Analysis', 'Budgeting', 'Reporting', 'PowerPoint'],
    salary_range: { min: 28000, max: 40000 },
    deadline: daysFromNow(50),
    application_url: 'https://absa.africa/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Registered Nurse – General Ward',
    type: 'full-time',
    company: 'Netcare St Augustine\'s Hospital',
    location: 'Durban, KwaZulu-Natal',
    province: ['KwaZulu-Natal'],
    description: 'Provide direct patient care in a busy general medical ward. Responsibilities include assessment, care planning, medication administration, wound care, and patient education. SANC registration required.',
    requirements: ['Diploma / Degree in Nursing', 'Current SANC registration', 'BLS / ACLS certification', 'At least 1 year clinical experience'],
    skills: ['Patient Care', 'Wound Care', 'Medication Administration', 'Clinical Assessment', 'SANC Registered'],
    salary_range: { min: 18000, max: 28000 },
    deadline: daysFromNow(30),
    application_url: 'https://netcare.co.za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Mathematics & Science Teacher',
    type: 'full-time',
    company: 'Curro Holdings',
    location: 'Centurion, Gauteng',
    province: ['Gauteng'],
    description: 'Teach Mathematics and Physical Sciences to Grade 10–12 learners at a leading independent school. You will develop lesson plans, prepare learners for NSC examinations, and participate in extra-curricular activities.',
    requirements: ['BEd or PGCE (Sciences/Maths)', 'SACE registration', 'Strong Matric subject results', '2+ years teaching experience preferred'],
    skills: ['Mathematics', 'Physical Sciences', 'Lesson Planning', 'CAPS Curriculum', 'Classroom Management', 'SACE Registered'],
    salary_range: { min: 20000, max: 32000 },
    deadline: daysFromNow(55),
    application_url: 'https://curro.co.za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Customer Service Representative',
    type: 'full-time',
    company: 'Capitec Bank',
    location: 'Johannesburg, Gauteng',
    province: ['Gauteng'],
    description: 'Assist clients with banking queries at a branch level. You will process transactions, open accounts, resolve complaints, and promote digital banking products. Excellent people skills and a passion for service are essential.',
    requirements: ['Matric', 'Numerically literate', 'South African ID', 'Clean credit record', 'Previous retail/banking experience advantageous'],
    skills: ['Customer Service', 'Banking', 'Cash Handling', 'Sales', 'Communication', 'Problem Solving'],
    salary_range: { min: 10000, max: 16000 },
    deadline: daysFromNow(25),
    application_url: 'https://capitecbank.co.za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Graphic Designer',
    type: 'full-time',
    company: 'Ogilvy South Africa',
    location: 'Cape Town, Western Cape',
    province: ['Western Cape'],
    description: 'Create compelling visual assets for multi-channel advertising campaigns. You will collaborate with copywriters and account teams to produce print, digital, and social media designs for blue-chip clients.',
    requirements: ['Diploma / Degree in Graphic Design', 'Adobe Creative Suite proficiency', 'Strong portfolio', '2+ years agency experience preferred'],
    skills: ['Adobe Photoshop', 'Adobe Illustrator', 'InDesign', 'Typography', 'Brand Design', 'Motion Graphics'],
    salary_range: { min: 18000, max: 28000 },
    deadline: daysFromNow(40),
    application_url: 'https://ogilvy.com/sa/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Frontend Developer Internship',
    type: 'internship',
    company: 'FNB Digital',
    location: 'Johannesburg, Gauteng',
    province: ['Gauteng'],
    description: '12-month paid internship within the digital banking product team. You will build React components, contribute to the design system, and participate in code reviews. A great launchpad for a career in fintech.',
    requirements: ['BSc Computer Science / relevant degree (final year or recent graduate)', 'HTML, CSS, JavaScript basics', 'Keen to learn React', 'Strong problem-solving skills'],
    skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Git', 'Agile'],
    salary_range: { min: 8000, max: 14000 },
    deadline: daysFromNow(45),
    application_url: 'https://fnb.co.za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Junior UX Designer',
    type: 'full-time',
    company: 'Yoco Technologies',
    location: 'Cape Town, Western Cape',
    province: ['Western Cape'],
    description: 'Design user experiences for Yoco\'s point-of-sale and business management products. You will conduct user research, create wireframes and prototypes, and collaborate with engineering to ship polished interfaces used by thousands of small businesses across Africa.',
    requirements: ['Portfolio demonstrating UX/UI work', 'Figma proficiency', 'User research skills', 'Design degree advantageous but not required'],
    skills: ['Figma', 'User Research', 'Wireframing', 'Prototyping', 'UI Design', 'Usability Testing'],
    salary_range: { min: 22000, max: 35000 },
    deadline: daysFromNow(50),
    application_url: 'https://yoco.com/za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Business Analyst',
    type: 'full-time',
    company: 'Accenture South Africa',
    location: 'Sandton, Gauteng',
    province: ['Gauteng'],
    description: 'Work with clients across banking, insurance, and public sector to define business requirements, map processes, and support digital transformation initiatives. You will produce business requirements documents, process flows, and user stories.',
    requirements: ['BCom / BSc degree', 'BABOK or similar certification preferred', '2+ years BA experience', 'Excellent communication skills'],
    skills: ['Business Analysis', 'Requirements Gathering', 'Process Mapping', 'Agile', 'SQL', 'Stakeholder Management'],
    salary_range: { min: 35000, max: 55000 },
    deadline: daysFromNow(60),
    application_url: 'https://accenture.com/za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Supply Chain Coordinator',
    type: 'full-time',
    company: 'Transnet Freight Rail',
    location: 'Durban, KwaZulu-Natal',
    province: ['KwaZulu-Natal'],
    description: 'Coordinate the movement of goods through the supply chain, liaising with suppliers, logistics partners, and internal stakeholders. You will track shipments, manage documentation, and optimise delivery performance.',
    requirements: ['Degree in Supply Chain / Logistics / Commerce', 'SAP knowledge advantageous', 'Attention to detail', '1–2 years experience'],
    skills: ['Supply Chain Management', 'Logistics', 'SAP', 'Excel', 'Inventory Management', 'Communication'],
    salary_range: { min: 20000, max: 30000 },
    deadline: daysFromNow(35),
    application_url: 'https://transnet.net/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Content Writer (Remote)',
    type: 'full-time',
    company: 'BrightRock Life',
    location: 'Remote (South Africa)',
    province: ['Gauteng', 'Western Cape', 'KwaZulu-Natal'],
    description: 'Produce long-form articles, web copy, email campaigns, and social media content for a leading life insurance brand. You will research complex financial topics and translate them into accessible, engaging content for South African consumers.',
    requirements: ['English degree / Journalism / Communications', 'Excellent written English', 'Financial services content experience advantageous', 'SEO knowledge'],
    skills: ['Copywriting', 'SEO', 'Content Strategy', 'Research', 'Microsoft Word', 'Financial Writing'],
    salary_range: { min: 18000, max: 28000 },
    deadline: daysFromNow(40),
    application_url: 'https://brightrock.co.za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Junior Data Scientist',
    type: 'full-time',
    company: 'Discovery Health',
    location: 'Sandton, Gauteng',
    province: ['Gauteng'],
    description: 'Apply machine learning and statistical techniques to healthcare datasets to improve member outcomes and operational efficiency. You will build predictive models, conduct exploratory data analysis, and present findings to clinical and actuarial teams.',
    requirements: ['BSc / Honours in Data Science, Statistics, or Maths', 'Python and R proficiency', 'Machine learning experience', 'Healthcare knowledge advantageous'],
    skills: ['Python', 'R', 'Machine Learning', 'SQL', 'Data Visualisation', 'Pandas', 'scikit-learn'],
    salary_range: { min: 30000, max: 50000 },
    deadline: daysFromNow(60),
    application_url: 'https://discovery.co.za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Graduate Engineering Programme',
    type: 'graduate',
    company: 'Eskom Holdings',
    location: 'Johannesburg, Gauteng',
    province: ['Gauteng', 'Limpopo', 'Mpumalanga'],
    description: '2-year structured graduate programme for newly qualified engineers. Graduates rotate through generation, transmission, and distribution divisions, gaining hands-on experience with South Africa\'s national power grid infrastructure under the mentorship of experienced engineers.',
    requirements: ['BEng / BSc Engineering (Electrical, Mechanical, or Civil)', 'South African citizen', 'Graduated within the last 2 years', 'Valid driver\'s licence'],
    skills: ['Electrical Engineering', 'Mechanical Engineering', 'AutoCAD', 'Project Management', 'Safety Standards', 'Technical Reporting'],
    salary_range: { min: 22000, max: 28000 },
    deadline: daysFromNow(75),
    application_url: 'https://eskom.co.za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Social Media Manager',
    type: 'full-time',
    company: 'Mr Price Group',
    location: 'Durban, KwaZulu-Natal',
    province: ['KwaZulu-Natal'],
    description: 'Lead the social media strategy for Mr Price\'s retail brands, managing communities across Instagram, Facebook, TikTok, and X. You will brief agency partners, respond to customer queries, and drive brand awareness campaigns for seasonal retail events.',
    requirements: ['Marketing / Communications degree', '3+ years social media management', 'Experience with social listening tools', 'Content creation skills'],
    skills: ['Social Media Strategy', 'Community Management', 'Content Creation', 'Analytics', 'TikTok', 'Brand Management'],
    salary_range: { min: 25000, max: 40000 },
    deadline: daysFromNow(30),
    application_url: 'https://mrprice.co.za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Network Administrator',
    type: 'full-time',
    company: 'MTN South Africa',
    location: 'Roodepoort, Gauteng',
    province: ['Gauteng'],
    description: 'Manage and maintain MTN\'s internal corporate network infrastructure including LAN, WAN, firewalls, and VPN. You will monitor network performance, troubleshoot outages, and implement security patches.',
    requirements: ['CCNA or equivalent certification', '2+ years network administration experience', 'Cisco or Fortinet experience', 'ITIL certification advantageous'],
    skills: ['Cisco Networking', 'Firewalls', 'VPN', 'Network Monitoring', 'TCP/IP', 'ITIL', 'Linux'],
    salary_range: { min: 25000, max: 40000 },
    deadline: daysFromNow(45),
    application_url: 'https://mtn.co.za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Accountant',
    type: 'full-time',
    company: 'PKF Octagon Inc.',
    location: 'Johannesburg, Gauteng',
    province: ['Gauteng'],
    description: 'Manage a portfolio of SME clients, preparing annual financial statements, tax returns, and management accounts. You will liaise directly with clients, SARS, and regulatory bodies. SAIPA or SAICA membership preferred.',
    requirements: ['BCom Accounting', 'SAIPA / SAICA registered or completing articles', 'Caseware experience', 'Tax knowledge (income tax, VAT)'],
    skills: ['Accounting', 'Caseware', 'SARS eFiling', 'IFRS', 'Tax Compliance', 'Financial Statements', 'Excel'],
    salary_range: { min: 25000, max: 45000 },
    deadline: daysFromNow(50),
    application_url: 'https://pkf.co.za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Project Administrator',
    type: 'full-time',
    company: 'Aurecon Group',
    location: 'Pretoria, Gauteng',
    province: ['Gauteng'],
    description: 'Support the project management team on large infrastructure and engineering projects. Responsibilities include scheduling, document control, stakeholder communications, and financial tracking using project management software.',
    requirements: ['Project Management diploma or BCom', 'MS Project or similar', 'Strong administrative skills', 'Construction/engineering exposure advantageous'],
    skills: ['Project Administration', 'MS Project', 'Document Control', 'Scheduling', 'Stakeholder Management', 'Excel'],
    salary_range: { min: 18000, max: 28000 },
    deadline: daysFromNow(35),
    application_url: 'https://aurecongroup.com/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Pharmacist',
    type: 'full-time',
    company: 'Clicks Group',
    location: 'Pretoria, Gauteng',
    province: ['Gauteng'],
    description: 'Dispense prescription medication, counsel patients on medicine usage, and ensure compliance with SAPC regulations at a busy community pharmacy. You will supervise pharmacy support staff and manage medicine stock levels.',
    requirements: ['BPharm degree', 'SAPC registration', 'Dispensing licence', 'Community pharmacy experience preferred'],
    skills: ['Pharmacy', 'Dispensing', 'Patient Counselling', 'SAPC Compliance', 'Stock Management', 'Chronic Medicine'],
    salary_range: { min: 35000, max: 55000 },
    deadline: daysFromNow(45),
    application_url: 'https://clicks.co.za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Operations Manager',
    type: 'full-time',
    company: 'Chicken Licken',
    location: 'Johannesburg, Gauteng',
    province: ['Gauteng'],
    description: 'Oversee day-to-day restaurant operations across a cluster of QSR outlets. You will manage staff rosters, drive sales performance, maintain food safety standards, and lead outlet managers to achieve operational KPIs.',
    requirements: ['Business / Hospitality Management degree', '3+ years QSR operations experience', 'P&L management exposure', 'Strong leadership skills'],
    skills: ['Operations Management', 'Team Leadership', 'P&L Management', 'Food Safety', 'Staff Training', 'Retail KPIs'],
    salary_range: { min: 30000, max: 50000 },
    deadline: daysFromNow(30),
    application_url: 'https://chickenlicken.co.za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Environmental Consultant',
    type: 'contract',
    company: 'SRK Consulting',
    location: 'Cape Town, Western Cape',
    province: ['Western Cape'],
    description: '12-month contract supporting Environmental Impact Assessment (EIA) projects for mining and renewable energy clients. You will conduct site assessments, compile reports, and engage with DFFE during the authorisation process.',
    requirements: ['BSc Environmental Science / Natural Sciences', '2+ years EIA experience', 'NEMA authorisation process knowledge', 'Valid driver\'s licence'],
    skills: ['Environmental Impact Assessment', 'EIA Reporting', 'NEMA', 'GIS', 'Stakeholder Engagement', 'Report Writing'],
    salary_range: { min: 30000, max: 50000 },
    deadline: daysFromNow(40),
    application_url: 'https://srk.com/za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Community Development Worker',
    type: 'full-time',
    company: 'NSFAS – National Student Financial Aid Scheme',
    location: 'Gqeberha (Port Elizabeth), Eastern Cape',
    province: ['Eastern Cape'],
    description: 'Conduct community outreach to educate students and families about NSFAS funding applications, assist with application processing, and refer students to relevant support services. You will work in underserved communities across the Eastern Cape.',
    requirements: ['Social Work / Development Studies degree', 'Experience in community facilitation', 'isiXhosa proficiency advantageous', 'Valid driver\'s licence'],
    skills: ['Community Development', 'Stakeholder Engagement', 'Public Speaking', 'Case Management', 'Report Writing', 'isiXhosa'],
    salary_range: { min: 12000, max: 18000 },
    deadline: daysFromNow(35),
    application_url: 'https://nsfas.org.za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Legal Secretary',
    type: 'full-time',
    company: 'Cliffe Dekker Hofmeyr',
    location: 'Pretoria, Gauteng',
    province: ['Gauteng'],
    description: 'Provide secretarial and administrative support to a team of attorneys in a large commercial law firm. Duties include drafting correspondence, managing diaries, preparing court documents, and liaising with clients and the courts.',
    requirements: ['Matric plus legal secretarial diploma', 'Proficiency in legal documentation', 'Excellent typing speed', '2+ years law firm experience'],
    skills: ['Legal Drafting', 'Court Filing', 'Diary Management', 'Microsoft Office', 'Legal Terminology', 'Document Management'],
    salary_range: { min: 14000, max: 22000 },
    deadline: daysFromNow(45),
    application_url: 'https://cdh.co.za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Software QA Tester (Remote)',
    type: 'full-time',
    company: 'Tangent Solutions',
    location: 'Remote (South Africa)',
    province: ['Gauteng', 'Western Cape', 'KwaZulu-Natal', 'Eastern Cape'],
    description: 'Test web and mobile applications for a software consultancy. You will write and execute manual test cases, manage defect tracking in Jira, and participate in agile ceremonies. Automation skills (Selenium/Cypress) are a bonus.',
    requirements: ['IT-related qualification', 'Manual testing experience', 'Jira or similar bug tracking', 'ISTQB certification advantageous'],
    skills: ['Manual Testing', 'Test Case Writing', 'Jira', 'Agile', 'Regression Testing', 'API Testing', 'Selenium'],
    salary_range: { min: 18000, max: 30000 },
    deadline: daysFromNow(50),
    application_url: 'https://tangentsolutions.co.za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Graduate Programme – Retail Banking',
    type: 'graduate',
    company: 'Standard Bank',
    location: 'Johannesburg, Gauteng',
    province: ['Gauteng'],
    description: '18-month graduate development programme in retail and business banking. Graduates rotate through branch banking, credit, and digital channels teams, complete structured learning modules, and are mentored by senior bankers. Top performers receive permanent placement.',
    requirements: ['BCom / BCompt / BSc (Finance, Economics, Accounting, or related) - NQF Level 7', 'Maximum 1 year since graduation', 'Strong academic record', 'South African citizen or permanent resident'],
    skills: ['Banking', 'Financial Analysis', 'Credit Assessment', 'Relationship Management', 'Excel', 'Communication'],
    salary_range: { min: 18000, max: 25000 },
    deadline: daysFromNow(60),
    application_url: 'https://standardbank.co.za/graduate-programme',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Mechatronics Technician',
    type: 'full-time',
    company: 'BMW Group Plant Rosslyn',
    location: 'Rosslyn, Gauteng',
    province: ['Gauteng'],
    description: 'Maintain and repair automated assembly line equipment including robotic welding cells, conveyor systems, and PLC-controlled machinery at BMW\'s South African manufacturing plant. Shift work required.',
    requirements: ['N3 + Trade Test (Millwright, Electrical, or Mechatronics)', '2+ years automotive manufacturing experience', 'Siemens / Allen-Bradley PLC knowledge', 'Shift work availability'],
    skills: ['PLC Programming', 'Robotics', 'Electrical Maintenance', 'Pneumatics', 'Hydraulics', 'Siemens TIA Portal'],
    salary_range: { min: 22000, max: 38000 },
    deadline: daysFromNow(30),
    application_url: 'https://bmwgroup.com/za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'Marketing Intern – 6 Month Contract',
    type: 'internship',
    company: 'Kaya FM',
    location: 'Johannesburg, Gauteng',
    province: ['Gauteng'],
    description: 'Support the marketing and events team at one of South Africa\'s most prominent urban radio stations. You will assist with event coordination, sponsor activations, social media scheduling, and internal brand campaigns.',
    requirements: ['Marketing / Comms degree or currently studying', 'Strong written and verbal communication', 'Social media savvy', 'Interest in media and entertainment'],
    skills: ['Marketing', 'Event Coordination', 'Social Media', 'Content Creation', 'Brand Campaigns', 'Communication'],
    salary_range: { min: 6000, max: 10000 },
    deadline: daysFromNow(25),
    application_url: 'https://kayafm.co.za/careers',
    is_active: true,
    source: 'seed',
  },
  {
    title: 'DevOps Engineer',
    type: 'full-time',
    company: 'Entelect Software',
    location: 'Johannesburg, Gauteng',
    province: ['Gauteng'],
    description: 'Build and maintain CI/CD pipelines, container infrastructure, and cloud environments for high-traffic software products. You will work with Azure/AWS, Kubernetes, and Terraform while collaborating with development squads to improve release velocity and reliability.',
    requirements: ['BSc/BEng Computer Science or equivalent', '3+ years DevOps / SRE experience', 'Kubernetes and Docker proficiency', 'Azure or AWS certification preferred'],
    skills: ['Kubernetes', 'Docker', 'CI/CD', 'Terraform', 'Azure', 'AWS', 'Linux', 'Python', 'Monitoring'],
    salary_range: { min: 45000, max: 70000 },
    deadline: daysFromNow(60),
    application_url: 'https://entelect.co.za/careers',
    is_active: true,
    source: 'seed',
  },
];

async function seedOpportunities() {
  const supabase = getSupabase();

  const { data, error } = await supabase
    .from('opportunities')
    .insert(OPPORTUNITIES)
    .select('id');

  if (error) {
    throw new Error(`Seed insert failed: ${error.message}`);
  }

  return { new: data?.length ?? 0 };
}

module.exports = { seedOpportunities };

// Allow running directly: node scripts/seedOpportunities.js
if (require.main === module) {
  seedOpportunities()
    .then(result => {
      console.log(`Seeded ${result.new} opportunities successfully.`);
      process.exit(0);
    })
    .catch(err => {
      console.error('Seeding failed:', err.message);
      process.exit(1);
    });
}
