// All 11 official languages of South Africa
export const SA_LANGUAGES = [
  "isiZulu",
  "isiXhosa",
  "Afrikaans",
  "English",
  "Sesotho sa Leboa",
  "Setswana",
  "Sesotho",
  "Xitsonga",
  "siSwati",
  "Tshivenda",
  "isiNdebele",
] as const;

export type SALanguage = (typeof SA_LANGUAGES)[number];

// Translations for all rotating phrases across all 11 official SA languages
export const translations: Record<string, Record<SALanguage, string>> = {
  ubuntuProverb: {
    isiZulu: "Umuntu ngumuntu ngabantu",
    isiXhosa: "Umntu ngumntu ngabantu",
    Afrikaans: "'n Mens is 'n mens deur ander mense",
    English: "A person is a person through other people",
    "Sesotho sa Leboa": "Motho ke motho ka batho",
    Setswana: "Motho ke motho ka batho ba bangwe",
    Sesotho: "Motho ke motho ka batho ba bang",
    Xitsonga: "Munhu i munhu hi vanhu",
    siSwati: "Umuntfu ngumuntfu ngebantfu",
    Tshivenda: "Muthu ndi muthu nga vhathu",
    isiNdebele: "Umuntu mumuntu ngabantu",
  },
  mahala: {
    isiZulu: "Mahala",
    isiXhosa: "Mahala",
    Afrikaans: "Gratis",
    English: "Free",
    "Sesotho sa Leboa": "Mahala",
    Setswana: "Mahala",
    Sesotho: "Mahala",
    Xitsonga: "Mahala",
    siSwati: "Mahala",
    Tshivenda: "Mahala",
    isiNdebele: "Mahala",
  },
  ubuntu: {
    isiZulu: "Ubuntu",
    isiXhosa: "Ubuntu",
    Afrikaans: "Medemenslikheid",
    English: "Humanity",
    "Sesotho sa Leboa": "Botho",
    Setswana: "Botho",
    Sesotho: "Botho",
    Xitsonga: "Vumunhu",
    siSwati: "Ubuntu",
    Tshivenda: "Vhuthu",
    isiNdebele: "Ubuntu",
  },
  ourTools: {
    isiZulu: "Izinsiza Zethu",
    isiXhosa: "Izixhobo Zethu",
    Afrikaans: "Ons Gereedskap",
    English: "Our Tools",
    "Sesotho sa Leboa": "Ditlabakelo tša Rena",
    Setswana: "Didiriswa tsa Rona",
    Sesotho: "Lisebelisoa tsa Rona",
    Xitsonga: "Switirhisiwa swa Hina",
    siSwati: "Emathuluzi Etfu",
    Tshivenda: "Zwishumiswa zwashu",
    isiNdebele: "Amathuluzi Wethu",
  },
  thePath: {
    isiZulu: "Indlela",
    isiXhosa: "Indlela",
    Afrikaans: "Die Pad",
    English: "The Path",
    "Sesotho sa Leboa": "Tsela",
    Setswana: "Tsela",
    Sesotho: "Tsela",
    Xitsonga: "Ndlela",
    siSwati: "Indlela",
    Tshivenda: "Nḓila",
    isiNdebele: "Indlela",
  },
  letsBegin: {
    isiZulu: "Siyaqala!",
    isiXhosa: "Siyaqala!",
    Afrikaans: "Ons Begin!",
    English: "Let's Begin!",
    "Sesotho sa Leboa": "Re a thoma!",
    Setswana: "Re a simolola!",
    Sesotho: "Re a qala!",
    Xitsonga: "Hi sungula!",
    siSwati: "Siyacala!",
    Tshivenda: "Ri a thoma!",
    isiNdebele: "Siyathoma!",
  },
  watch: {
    isiZulu: "Buka",
    isiXhosa: "Bukela",
    Afrikaans: "Kyk",
    English: "Watch",
    "Sesotho sa Leboa": "Bogela",
    Setswana: "Bogela",
    Sesotho: "Sheba",
    Xitsonga: "Languta",
    siSwati: "Buka",
    Tshivenda: "Lavhelesa",
    isiNdebele: "Bukela",
  },
  successStories: {
    isiZulu: "Izindaba Zempumelelo",
    isiXhosa: "Amabali Empumelelo",
    Afrikaans: "Suksesverhale",
    English: "Success Stories",
    "Sesotho sa Leboa": "Dikanegelo tša Katlego",
    Setswana: "Dikgang tsa Katlego",
    Sesotho: "Lipale tsa Katleho",
    Xitsonga: "Mintsheketo ya Ku Humelela",
    siSwati: "Tindzaba Tekuphumelela",
    Tshivenda: "Nyambedzano dza u Bvelela",
    isiNdebele: "Iindaba Zokuphumelela",
  },
  poweredBy: {
    isiZulu: "Amandla e-Ubuntu",
    isiXhosa: "Amandla e-Ubuntu",
    Afrikaans: "Aangedryf deur Ubuntu",
    English: "Powered by Ubuntu",
    "Sesotho sa Leboa": "Maatla a Botho",
    Setswana: "Maatla a Botho",
    Sesotho: "Matla a Botho",
    Xitsonga: "Matimba ya Vumunhu",
    siSwati: "Emandla e-Ubuntu",
    Tshivenda: "Maanḓa a Vhuthu",
    isiNdebele: "Amandla we-Ubuntu",
  },
};
